import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./global.scss";
import { getServerSession } from "next-auth";
import SessionProvider from "@/providers/SessionProvider";
import ReduxProvider from "@/providers/ReduxProvider";
import LayoutClient from "./layout.client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EcoMovie",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <>
          <SessionProvider session={session}>
            <LayoutClient>{children}</LayoutClient>
          </SessionProvider>
        </>
      </body>
    </html>
  );
}
